apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
       app: pro-deployment
  template:
    metadata:
      labels:
        app: pro-deployment
    spec:
      containers:
      - name: pro-cont
        image: pro:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
      - args:
        - /run.sh
        resources:
         limits:
           cpu: "0.5"
        image: cassandra:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        name: cassandra
        ports:
        - name: cql
          containerPort: 9042
        - name: thrift
          containerPort: 9160
        # volumeMounts:
         #- name: data
         #  mountPath: /cassandra_data
        env:
        - name: MAX_HEAP_SIZE
          value: 512M
        - name: HEAP_NEWSIZE
          value: 100M
        - name: POD_NAMESPACE
          valueFrom:
           fieldRef:
             fieldPath: metadata.namespace
